global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['s1:9100']
  - job_name: 'systemd'
    scrape_interval: 5s
    static_configs:
      - targets: ['s1:9558']
