global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-13-114-102-15.ap-northeast-1.compute.amazonaws.com:9100']
