services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-data:/prometheus'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - type: bind
        source: './grafana/datasources'
        target: '/etc/grafana/provisioning/datasources'
      - type: bind
        source: './grafana/dashboard-settings'
        target: '/etc/grafana/provisioning/dashboards'
      - type: bind
        source: './grafana/dashboards'
        target: '/var/lib/grafana/dashboards'

volumes:
  prometheus-data: {}
  grafana-data: {}
